name: actions
description: Frontend app for Actions
publish_to: none
version: 0.0.1+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  http: ^1.1.0
  dafluta: ^5.1.1
  just_audio: ^0.9.35
  volume_controller: ^2.0.7

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  lints: ^3.0.0
  daunused: ^1.3.0
  dapublock: ^1.0.1
  build_runner: ^2.4.6
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true